sudo: required
services:
  - docker 

before_install:
  - docker build -t julianijere/learning -f Dockerfile.dev .

script:
  - docker run julianijere/learning npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "learning-app"
  env: "LearningApp-env"
  bucket_name: "elasticbeanstalk-eu-west-2-324441702365"
  bucket_path: "learning-app"
  
  on:
    branch: master
  
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"